DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

DROP TABLE ANSWERBOARD;
-- 글번호 그룹번호 그룹순서 제목탭 제목 내용 작성자 작성일
CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, TITLE, CONTENT, WRITER, REGDATE 
FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSEQ;

--1번 글 작성
INSERT INTO ANSWERBOARD 
VALUES (BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '첫번째 글', '첫번째 글입니다', '관리자', SYSDATE);

--2번 글 작성
INSERT INTO ANSWERBOARD 
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0,'두번째 글', '두번째 글입니다', '작성자',SYSDATE);

--1번 글에 답변 작성
--부모의 글과 같은 그룹에서 부모의 순서 다음 순서에 있는 글들의 순서+1
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1) --BOARDNO = 1인 글의 GROUPNO (해당 글의 그룹번호에)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1); --BOARDNO가 1보다 큰 글들의 GROUPSEQ (해당글 이후 글들의 그룹내 순서)

--답변글 -> 부모글 = GROUPNO, 부모의 GROUPSEQ +1, 부모의 TITLETAB +1)
INSERT INTO ANSWERBOARD
VALUES (
	BOARDNOSEQ.NEXTVAL, 
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 1)+1, 
	'RE:첫번째글', 
	'첫번째 답변글안에', 
	'답변1', 
	SYSDATE
);
--1-2(3번 글 BOARDNO =3)에 다시 답변
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 3)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=3);

INSERT INTO ANSWERBOARD
VALUES (
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 3),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 3)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 3)+1,
	'RE:RE:첫번째 글',
	'1-2에 답변',
	'답변 1-1',
	SYSDATE
);


--1번글에 새로운 답변
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1);

INSERT INTO ANSWERBOARD
VALUES (
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
	'RE:첫번째글 - 이제 2번째',
	'GETTING A LITTLE CLEAR',
	'답변 1',
	SYSDATE
);

INSERT INTO ANSWERBOARD
VALUES ( 8,3,2,1,'RE:3번 글입니다','조심하라구','UNKNOWN2',SYSDATE);